title: Filip Cynarski Software Development
description: > # this means to ignore newlines until "baseurl:"
  Software Development, software quality expert, test automation, smart home solutions.
  Oprogramowanie komputerowe, procesy jakości oprogramowania, testowanie oprogramowania oraz automatyzacja testów.
permalink: ':title/'
baseurl: ""
url: "https://cynarski.eu"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Filip Cynarski
author-img: filip-cynarski.png
about-author: I am an experienced Software Engineer in Test / Test Lead. I've started programming when I was 12-years old and still enjoying an exciting journey of how the IT market is evolving.
social-github: filipcynarski
social-linkedin: filip-cynarski-39b3b260
social-email: filip@cynarski.eu

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
